[supervisord]
nodaemon=true
user=root
loglevel=debug

[program:xvfb]
# Move to :99 to avoid conflict with host :0 and :1
command=/bin/bash -c "rm -f /tmp/.X99-lock; exec Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +extension RANDR +render -noreset"
environment=LIBGL_ALWAYS_SOFTWARE="1"
autorestart=true
priority=1

[program:fluxbox]
command=fluxbox -display :99
environment=DISPLAY=":99"
autorestart=true
priority=2

[program:x11vnc]
# Force port 5999 to avoid "Address already in use" on 5900
command=x11vnc -display WAIT:99 -forever -shared -nopw -noshm -noxdamage -rfbport 5999 -bg
autorestart=true
priority=3

[program:novnc]
# Tell noVNC to connect to the new port 5999
command=/opt/noVNC/utils/novnc_proxy --vnc localhost:5999 --listen 6080
autorestart=true
priority=4
